---
# Organization-wide label definitions
# These labels are referenced in issue templates and should be available across all repositories

# Type labels - categorize the kind of work
- name: type:bug
  description: Something is broken or incorrect
  color: d73a4a

- name: type:feature
  description: Parent feature / epic
  color: 5319e7

- name: type:task
  description: Implementation task
  color: 1d76db

- name: type:research
  description: Research or investigation task
  color: fbca04
