name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true
  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to see
    validations:
      required: true
  
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually occurred
    validations:
      required: true
  
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide information about your environment
      placeholder: |
        - OS: [e.g., Windows 11, macOS 13.0, Ubuntu 22.04]
        - Browser: [e.g., Chrome 120, Firefox 121]
        - Version: [e.g., v1.0.0]
      value: |
        - OS: 
        - Browser: 
        - Version: 
    validations:
      required: false
  
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Screenshots
      description: Add any relevant logs, error messages, or screenshots
      placeholder: Paste logs or drag and drop screenshots here
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Any additional information that might be helpful
    validations:
      required: false
