name: Research
description: Investigate unknowns before implementation
title: "research: "
labels: ["type:research"]
body:
  - type: input
    id: feature_slug
    attributes:
      label: Feature Slug
      description: Slug of the parent feature (used for branch/plan linking).
      placeholder: "oauth-token-refresh"
    validations:
      required: true

  - type: input
    id: parent
    attributes:
      label: Parent Feature Issue
      description: Link the parent feature issue (recommended).
      placeholder: "#123"
    validations:
      required: false

  - type: textarea
    id: question
    attributes:
      label: Research Question
      description: What do we need to learn/decide?
      placeholder: "What is the best way to X given constraints Y?"
    validations:
      required: true

  - type: textarea
    id: success
    attributes:
      label: Done Means
      description: What artifact will this produce?
      placeholder: |
        - docs/research/<topic>.md with:
          - verified facts + sources
          - unknowns explicitly labeled
          - recommended approach
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context / Background
      description: Only what is necessary. Link docs/issues/PRs.
      placeholder: |
        - Related: #123
        - Plan: plans/<feature-slug>.md — R1
        - Notes: ...
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: Scope / Constraints
      placeholder: |
        In scope:
        - ...
        Out of scope:
        - ...
    validations:
      required: false

  - type: input
    id: artifacts
    attributes:
      label: Artifacts / Links
      description: Where the research will live (or related links).
      placeholder: "docs/research/<topic>.md"
    validations:
      required: false

  - type: dropdown
    id: timebox
    attributes:
      label: Timebox
      options:
        - 30 minutes
        - 1 hour
        - 2 hours
        - 4 hours
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 (urgent)
        - P1 (high)
        - P2 (medium)
        - P3 (low)
    validations:
      required: false

  - type: input
    id: owner
    attributes:
      label: Owner
      description: GitHub username (optional).
      placeholder: "@your-handle"
    validations:
      required: false
